### PR TITLE
Fix related to the revert #715

### PR DESCRIPTION
**Pull request by ebocher**
It's preferable to use a single method in the dbmanager to detect the db type.

### CODE REVIEW

**Comment by ebocher** [comment]
Ready to merge

**Comment by nicolas-f** [comment]
Yes, it's more clean than rely on non-standard jdbc properties

**Comment by nicolas-f** [comment]
Please fetch and checkout from github/orbisgis/master on your pc before making new commits

**Comment by ebocher** [comment]
What ?

**Pull request merged**
