### PR TITLE
A proposal to use featurevisitor.

### PR DESCRIPTION
**Pull request by ebocher**
The gain is not visible :-(
About  #855

### CODE REVIEW

**Comment by ebocher** [comment]
Note that the Thread.sleep with ProgressMonitor seems also a cause of slow down (tested with visualvm).

**Comment by ebocher** [comment]
Ping

**Comment by nicolas-f** [comment]
You do not filter in ReadRowSet. May be this is why you don't have better performance

**Comment by ebocher** [comment]
You mean CachedResultSetContainerif
```java
getResultSetProvider(ILayer layer, ProgressMonitor pm)...

(integerPK.isEmpty()) {                        
                        readRowSet.setCommand("SELECT " + defaultResultSetProvider.getPkName() + ", * FROM "+tableRef);
                    }
```

**Pull request merged**
