### PR TITLE
Toggle geometies in table editor.

### PR DESCRIPTION
**Pull request by SPalominos**
Some improvement to make the sorting of the table editor faster. #997 
- Move the RefreshTableJob and CloseTableEditorJob into their own file.
- Change the core-jdbc and editor-jdbc bundles to be able to indicate to the ReadRowSet interface if the geometric fields should be ignored or not.
- Updates the tablegui bundle to add an icon that will toogle the display and the requesting of the geometric fields
- The chaching of PK on sort can be cancelled.

@ebocher @nicolas-f  Any comment or review ?

### CODE REVIEW

**Comment by ebocher** [comment]
Very good job and nice idea about geometry. Some remarks
1. When a sort is running  is not possible to stop the caching of primary key values
2. The toggle geometry button must be disable when the table doesn't contain a geometry column
3. Open a large table  (more than one millions of rows) take a lot time. I think a limit clause must be added the first time ?

**Comment by SPalominos** [comment]
@ebocher  Ok, I'll work on those changes.

**Comment by SPalominos** [comment]
@ebocher The fixes requested are done, the geometry toggle is hidden if not available, the caching of PK on sort can be cancelled and by default the geometries are hidden except if there is only geometric field in the table.

**Comment by SPalominos** [comment]
Last bug fixed, ready to be merged.

**Comment by SPalominos** [comment]
Make the request of PK lighter on sorting a table. [Here](https://drive.google.com/open?id=1bsGuX0_Nbuev3rGEXhYGP5RqIdm1-IJl) is a built version of OrbisGIS to be tested if needed.

**Comment by ebocher** [comment]
clap clap

**Pull request merged**
