### PR TITLE
Fix shell scripts so that they can be called outside the install.dir.

### PR DESCRIPTION
**Pull request by sbigaret**
cf. Issue #1015

### CODE REVIEW

**Comment by ebocher** [comment]
Before testing. Could please take into account the bat files ?

**Comment by ebocher** [comment]
@SPalominos 
Ok to merge ?

**Comment by SPalominos** [comment]
Yes, @sbigaret could you update this branch?

**Comment by sbigaret** [comment]
I've updated it, and added the same for batch files on Windows

**Comment by SPalominos** [comment]
Thank you very much @sbigaret !

**Pull request merged**
