### PR TITLE
About #1304 keep creating fence even if user zoom in/out or drag

### PR DESCRIPTION
**Pull request by nicolas-f**
keep creating fence even if user zoom in/out or drag

### CODE REVIEW

**Comment by nicolas-f** [comment]
Failure to find org.orbisgis:h2gis-utilities:jar:1.5.0-SNAPSHOT

**Comment by ebocher** [comment]
Yes the repository must be updated in the pom as here https://github.com/orbisgis/h2gis/pull/905/files

**Comment by ebocher** [comment]
Sorry about this issue

**Comment by ebocher** [comment]
You can add it into your pom

**Comment by ebocher** [comment]
Nice

**Pull request merged**
