### PR TITLE
Fix TableEditor Algo Error exception and row offset on search

### PR DESCRIPTION
**Pull request by nicolas-f**
- Fix row index finding from pk, optimised it 
- Fix offset in selection of TableEditor about #933

### CODE REVIEW

**Comment by ebocher** [comment]
Could you push also on master ?

**Comment by nicolas-f** [comment]
Nope, this change affect ReadRowSetImpl, heavily changed in this branch.

**Comment by nicolas-f** [comment]
I will not have the time to merge master to raster until next week.

**Comment by ebocher** [comment]
Ok. I understand.

**Pull request merged**
