### PR TITLE
WPS identifier.

### PR DESCRIPTION
**Pull request by SPalominos**
Change the way that the identifier are managed, see issue #1209.

### CODE REVIEW

**Comment by ebocher** [comment]
This PR will break the rigth-clic processes available in the geocatalog and on the table editor.

**Comment by SPalominos** [comment]
No, as the identifiers of the processes were updated, it still works.

**Comment by ebocher** [comment]
Maybe I'm wrong but in geocatalog , openTool method, you have
 URI inputDataStoreURI = URI.create("orbisgis:wps:official:geometryProperties:inputDataStore");
URI geometricFieldURI = URI.create("orbisgis:wps:official:geometryProperties:geometricField");

and you set in this PR
 dataTypes = ["GEOMETRY"],
-        identifier = "orbisgis:wps:official:geometryProperties:inputJDBCTable")
+        identifier = "inputJDBCTable")

**Comment by ebocher** [comment]
Did you fix the URI identifier in OrbisGIS geocatalog and tableeditor ?

**Comment by SPalominos** [comment]
The URI issue in the table-editor is fixed, and the tools from the geocatalog are removed.

**Pull request merged**
