### PR TITLE
OrbisToolBox data model

### PR DESCRIPTION
**Pull request by SPalominos**
Implements the data model for the description of a WPS Process (issue #835).
All the class come from the [WPS 2.0]( http://docs.opengeospatial.org/is/14-065/14-065.html#18) specification.

### CODE REVIEW

**Comment by ebocher** [comment]
Whaoou excellent.
Is it possible to add some basic groovy script examples or did you plan to create a new PR for that ?

**Comment by SPalominos** [comment]
The groovy annotations and example scripts will come quickly in a new PR as I need to check that they contain enough information to be parsed as a valid process.
Then, the parsing part will come.

**Comment by ebocher** [comment]
ok thanks

**Comment by SPalominos** [comment]
If it's OK, could you validate the PR ? ;-)

**Pull request merged**
