### PR TITLE
Default to display only compatible plugins

### PR DESCRIPTION
**Pull request by nicolas-f**
In the plugin manager, the remote list of plugins now display only the compatible plugins (can be installed and resolved dependency)

The list of plugins are now downloaded only when the user first open the plugin manager.

Change the radio button text "Available" to "Compatible"

Checking dependencies take time, so a progress information is displayed.

### CODE REVIEW

**Comment by ebocher** [comment]
nice
@SPalominos  ?

**Comment by SPalominos** [comment]
@nicolas-f What about CPU usage and its impact on user as you said in #1307 ?

**Comment by nicolas-f** [comment]
@SPalominos In order to reduce the inconvenience, computation of plugins dependencies are only done when the user open the plugin manager for the first time in the OrbisGIS session.

**Comment by ebocher** [comment]
Sounds good for me

**Pull request merged**
